POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Bob James",
  "username": "bob@bob.com"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "John Smith",
  "username": "john@smith.com"
}

###
GET http://localhost:3001/api/users
Content-Type: application/json
