POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "bob@bob.com",
  "password": "secret"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYkBib2IuY29tIiwiaWQiOjEsImlhdCI6MTY0OTY3OTYxMywiZXhwIjoxNjQ5NjgzMjEzfQ.njgDcRRkTS-pYlkDKEymRkKt94xnwj-2OdICr4GsvPM

{
    "author": "Bob aaba",
    "url": "bob.com",
    "title": "Bob part 1",
    "likes": 3,
    "year": 2022
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "secret"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5Ac21pdGguY29tIiwiaWQiOjIsImlhdCI6MTY0OTU1NTE1M30.rncGOy6vGT-EzAxRhZc4m_OS9Wx-4b7l9TG8oe13hkI

{
    "author": "John aaba",
    "url": "john.com",
    "title": "Johns part 2",
    "likes": 5,
    "year": 2022
}

###
GET  http://localhost:3001/api/blogs
Content-Type: application/json

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "John aaba",
    "url": "john.com",
    "title": "Johns part session",
    "likes": 9,
    "year": 2022
}
