POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "bob@bob.com",
  "password": "secret"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "john@smith.com",
  "password": "secret"
}
